baseURL = 'https://desm.cloud/'
languageCode = 'en-us'
title = 'Democratize Streaming'
theme = 'ananke'

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
favicon = "/favicon.ico"
commentoEnable = true

[services.disqus]
shortname = 'desm-cloud'

